#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int theme_custom_background = 2130771968;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int blank = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int WrongAnswer1 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int WrongAnswer2 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int WrongAnswer3 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int WrongAnswer4 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int WrongAnswer5 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int WrongAnswer6 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int WrongAnswer7 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int WrongAnswer8 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030002
			public const int btn_A = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btn_B = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btn_C = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int btn_D = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int btn_Delete = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int btn_E = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int btn_Exit = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int btn_F = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int btn_G = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int btn_H = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int btn_High_Score = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int btn_Home = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int btn_Home_Page = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int btn_I = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int btn_J = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int btn_K = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int btn_L = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int btn_M = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int btn_N = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int btn_New_Game = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int btn_O = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int btn_P = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int btn_Play_Game = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int btn_Q = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int btn_R = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int btn_S = 2130903067;
			
			// aapt resource value: 0x7F030023
			public const int btn_save = 2130903075;
			
			// aapt resource value: 0x7F03001C
			public const int btn_T = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int btn_U = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int btn_V = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int btn_W = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int btn_X = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int btn_Y = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int btn_Z = 2130903074;
			
			// aapt resource value: 0x7F030024
			public const int img_wrongs = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int linearLayout1 = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int linearLayout2 = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int linearLayout20 = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int linearLayout3 = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int linearLayout30 = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int linearLayout4 = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int linearLayout40 = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int linearLayout5 = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int linearLayout50 = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int linearLayout6 = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int linearLayout70 = 2130903087;
			
			// aapt resource value: 0x7F030000
			public const int Lv_HighScore = 2130903040;
			
			// aapt resource value: 0x7F030030
			public const int spinner_select = 2130903088;
			
			// aapt resource value: 0x7F030001
			public const int Spinnner_select = 2130903041;
			
			// aapt resource value: 0x7F030031
			public const int textView1 = 2130903089;
			
			// aapt resource value: 0x7F030032
			public const int textView35 = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int txtCurrentScore = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int txtGuessesLeft = 2130903092;
			
			// aapt resource value: 0x7F03003B
			public const int txtrowId = 2130903099;
			
			// aapt resource value: 0x7F030035
			public const int txtRowName = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int txtRowScore = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int txtWordToGuess = 2130903095;
			
			// aapt resource value: 0x7F030038
			public const int txt_Name = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int txt_title = 2130903097;
			
			// aapt resource value: 0x7F03003A
			public const int txt_view_title = 2130903098;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Delete_Record = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int listview_row = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Main_Page = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int New_Palyer = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int Play_Game = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int View_High_Scores = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
